eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    
microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://DiscoveryClient_PAYMENT-SERVICE/Deepak-Singla-PC:PAYMENT-SERVICE:9191/payment/doPayment
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/bookOrder    
